-- Football Network: global geographic and club-data backbone.
-- Additive, idempotent and designed for bulk imports with traceable sources.

begin;

create extension if not exists unaccent with schema extensions;
create extension if not exists pg_trgm with schema extensions;

create table if not exists data_sources (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  website_url text not null,
  license_name text,
  license_url text,
  attribution_text text,
  terms_url text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into data_sources(slug,name,website_url,license_name,license_url,attribution_text,terms_url)
values
  ('geonames','GeoNames','https://www.geonames.org/','CC BY 4.0','https://creativecommons.org/licenses/by/4.0/','Geographic data provided by GeoNames.','https://www.geonames.org/export/'),
  ('wikidata','Wikidata','https://www.wikidata.org/','CC0 1.0','https://creativecommons.org/publicdomain/zero/1.0/','Structured data provided by Wikidata.','https://foundation.wikimedia.org/wiki/Policy:Terms_of_Use/'),
  ('openstreetmap','OpenStreetMap','https://www.openstreetmap.org/','ODbL 1.0','https://opendatacommons.org/licenses/odbl/1-0/','Data © OpenStreetMap contributors.','https://www.openstreetmap.org/copyright'),
  ('national_federation','National football federations','https://www.fifa.com/about-fifa/associations','Source-specific','https://www.fifa.com/legal','Club records verified against official federation publications when available.','https://www.fifa.com/legal')
on conflict(slug) do update set
  name=excluded.name,
  website_url=excluded.website_url,
  license_name=excluded.license_name,
  license_url=excluded.license_url,
  attribution_text=excluded.attribution_text,
  terms_url=excluded.terms_url,
  updated_at=now();

create or replace function normalize_search_text(value text)
returns text
language sql
stable
parallel safe
set search_path=public,extensions
as $$
  select trim(regexp_replace(lower(unaccent(coalesce(value,''))),'[^a-z0-9]+',' ','g'));
$$;

create table if not exists geographic_places (
  id bigint generated by default as identity primary key,
  source_id bigint not null references data_sources(id),
  source_key text not null,
  country_code text not null,
  postal_code text,
  place_name text not null,
  normalized_place_name text not null default '',
  admin_name1 text,
  admin_code1 text,
  admin_name2 text,
  admin_code2 text,
  admin_name3 text,
  admin_code3 text,
  latitude numeric(10,7),
  longitude numeric(10,7),
  accuracy smallint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source_id,source_key)
);

create table if not exists place_aliases (
  id bigint generated by default as identity primary key,
  geographic_place_id bigint not null references geographic_places(id) on delete cascade,
  alias text not null,
  normalized_alias text not null default '',
  locale text,
  source_id bigint references data_sources(id),
  created_at timestamptz not null default now(),
  unique(geographic_place_id,normalized_alias)
);

create or replace function prepare_geographic_place_search()
returns trigger
language plpgsql
set search_path=public,extensions
as $$
begin
  new.country_code:=upper(left(trim(coalesce(new.country_code,'')),2));
  new.postal_code:=nullif(upper(trim(coalesce(new.postal_code,''))), '');
  new.normalized_place_name:=normalize_search_text(new.place_name);
  new.updated_at:=now();
  return new;
end;
$$;

drop trigger if exists geographic_place_search_trigger on geographic_places;
create trigger geographic_place_search_trigger
before insert or update of country_code,postal_code,place_name on geographic_places
for each row execute function prepare_geographic_place_search();

create or replace function prepare_place_alias_search()
returns trigger
language plpgsql
set search_path=public,extensions
as $$
begin
  new.normalized_alias:=normalize_search_text(new.alias);
  return new;
end;
$$;

drop trigger if exists place_alias_search_trigger on place_aliases;
create trigger place_alias_search_trigger
before insert or update of alias on place_aliases
for each row execute function prepare_place_alias_search();

create index if not exists idx_geographic_places_country_postal
  on geographic_places(country_code,postal_code);
create index if not exists idx_geographic_places_country_name
  on geographic_places(country_code,normalized_place_name);
create index if not exists idx_geographic_places_name_trgm
  on geographic_places using gin(normalized_place_name extensions.gin_trgm_ops);
create index if not exists idx_place_aliases_name_trgm
  on place_aliases using gin(normalized_alias extensions.gin_trgm_ops);

alter table clubs
  add column if not exists postal_code text,
  add column if not exists address_line text,
  add column if not exists admin1_code text,
  add column if not exists admin2_code text,
  add column if not exists latitude numeric(10,7),
  add column if not exists longitude numeric(10,7),
  add column if not exists geographic_place_id bigint references geographic_places(id) on delete set null,
  add column if not exists normalized_name text not null default '',
  add column if not exists normalized_city text not null default '',
  add column if not exists search_vector tsvector,
  add column if not exists canonical_key text,
  add column if not exists source_priority integer not null default 100,
  add column if not exists last_synced_at timestamptz;

create table if not exists club_aliases (
  id bigint generated by default as identity primary key,
  club_id uuid not null references clubs(id) on delete cascade,
  alias_name text not null,
  normalized_alias text not null default '',
  locale text,
  source_id bigint references data_sources(id),
  created_at timestamptz not null default now(),
  unique(club_id,normalized_alias)
);

create table if not exists club_external_ids (
  id bigint generated by default as identity primary key,
  club_id uuid not null references clubs(id) on delete cascade,
  source_id bigint not null references data_sources(id),
  external_id text not null,
  source_url text,
  raw_hash text,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(source_id,external_id)
);

create table if not exists data_import_jobs (
  id uuid primary key default uuid_generate_v4(),
  source_id bigint not null references data_sources(id),
  import_type text not null,
  country_code text,
  status text not null default 'pending',
  rows_read integer not null default 0,
  rows_inserted integer not null default 0,
  rows_updated integer not null default 0,
  rows_rejected integer not null default 0,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  constraint data_import_jobs_status_check check(status in ('pending','running','completed','failed','cancelled'))
);

create table if not exists club_import_staging (
  id bigint generated by default as identity primary key,
  import_job_id uuid not null references data_import_jobs(id) on delete cascade,
  source_id bigint not null references data_sources(id),
  external_id text,
  raw_name text not null,
  normalized_name text not null default '',
  country_code text,
  city text,
  normalized_city text not null default '',
  postal_code text,
  latitude numeric(10,7),
  longitude numeric(10,7),
  website_url text,
  source_url text,
  raw_data jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  matched_club_id uuid references clubs(id) on delete set null,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint club_import_staging_status_check check(status in ('pending','matched','created','rejected','review'))
);

create table if not exists club_merge_candidates (
  id bigint generated by default as identity primary key,
  staging_id bigint not null references club_import_staging(id) on delete cascade,
  candidate_club_id uuid not null references clubs(id) on delete cascade,
  match_score numeric(5,4) not null,
  match_reasons jsonb not null default '[]'::jsonb,
  status text not null default 'pending',
  reviewed_by uuid references profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(staging_id,candidate_club_id),
  constraint club_merge_candidates_status_check check(status in ('pending','accepted','rejected'))
);

create or replace function prepare_club_search()
returns trigger
language plpgsql
set search_path=public,extensions
as $$
begin
  new.normalized_name:=normalize_search_text(concat_ws(' ',new.official_name,new.short_name));
  new.normalized_city:=normalize_search_text(new.city);
  new.postal_code:=nullif(upper(trim(coalesce(new.postal_code,''))), '');
  new.canonical_key:=normalize_search_text(concat_ws(' ',new.official_name,new.city,new.postal_code));
  new.search_vector:=to_tsvector('simple',concat_ws(' ',new.official_name,new.short_name,new.city,new.region,new.postal_code));
  return new;
end;
$$;

drop trigger if exists club_search_prepare_trigger on clubs;
create trigger club_search_prepare_trigger
before insert or update of official_name,short_name,city,region,postal_code on clubs
for each row execute function prepare_club_search();

create or replace function prepare_club_alias_search()
returns trigger
language plpgsql
set search_path=public,extensions
as $$
begin
  new.normalized_alias:=normalize_search_text(new.alias_name);
  return new;
end;
$$;

drop trigger if exists club_alias_search_trigger on club_aliases;
create trigger club_alias_search_trigger
before insert or update of alias_name on club_aliases
for each row execute function prepare_club_alias_search();

update geographic_places
set normalized_place_name=normalize_search_text(place_name)
where normalized_place_name='' or normalized_place_name is null;

update clubs set
  normalized_name=normalize_search_text(concat_ws(' ',official_name,short_name)),
  normalized_city=normalize_search_text(city),
  canonical_key=normalize_search_text(concat_ws(' ',official_name,city,postal_code)),
  search_vector=to_tsvector('simple',concat_ws(' ',official_name,short_name,city,region,postal_code))
where normalized_name='' or normalized_city='' or search_vector is null or canonical_key is null;

create index if not exists idx_clubs_search_vector on clubs using gin(search_vector);
create index if not exists idx_clubs_normalized_name_trgm on clubs using gin(normalized_name extensions.gin_trgm_ops);
create index if not exists idx_clubs_normalized_city on clubs(normalized_city);
create index if not exists idx_clubs_postal_code on clubs(postal_code);
create index if not exists idx_clubs_canonical_key on clubs(canonical_key);
create index if not exists idx_club_aliases_name_trgm on club_aliases using gin(normalized_alias extensions.gin_trgm_ops);
create index if not exists idx_import_jobs_status on data_import_jobs(status,created_at desc);
create index if not exists idx_club_staging_match on club_import_staging(country_code,normalized_city,normalized_name);
create index if not exists idx_club_merge_pending on club_merge_candidates(status,match_score desc);

create or replace function search_places(
  p_query text default '',
  p_country text default '',
  p_limit integer default 15
)
returns jsonb
language plpgsql
stable
security definer
set search_path=public,extensions
as $$
declare
  safe_query text:=normalize_search_text(left(trim(coalesce(p_query,'')),120));
  safe_country text:=upper(left(trim(coalesce(p_country,'')),2));
  safe_limit integer:=greatest(1,least(coalesce(p_limit,15),50));
  result jsonb;
begin
  if char_length(safe_query)<2 and char_length(safe_country)<>2 then
    return '[]'::jsonb;
  end if;

  with matched as (
    select gp.country_code,gp.postal_code,gp.place_name,gp.admin_name1,gp.admin_name2,gp.latitude,gp.longitude,
      case
        when normalize_search_text(coalesce(gp.postal_code,''))=safe_query then 100
        when gp.normalized_place_name=safe_query then 95
        when normalize_search_text(coalesce(gp.postal_code,'')) like safe_query||'%' then 90
        when gp.normalized_place_name like safe_query||'%' then 85
        else greatest(similarity(gp.normalized_place_name,safe_query),0)*70
      end as rank_score
    from geographic_places gp
    where (safe_country='' or gp.country_code=safe_country)
      and (
        safe_query=''
        or normalize_search_text(coalesce(gp.postal_code,'')) like safe_query||'%'
        or gp.normalized_place_name like safe_query||'%'
        or gp.normalized_place_name % safe_query
        or exists(select 1 from place_aliases pa where pa.geographic_place_id=gp.id and (pa.normalized_alias like safe_query||'%' or pa.normalized_alias % safe_query))
      )
  ), deduplicated as (
    select distinct on(country_code,postal_code,place_name,admin_name1)
      country_code,postal_code,place_name,admin_name1,admin_name2,latitude,longitude,rank_score
    from matched
    order by country_code,postal_code,place_name,admin_name1,rank_score desc
  )
  select coalesce(jsonb_agg(to_jsonb(ranked) order by rank_score desc,place_name,postal_code),'[]'::jsonb)
  into result
  from (select * from deduplicated order by rank_score desc,place_name,postal_code limit safe_limit) ranked;

  return coalesce(result,'[]'::jsonb);
end;
$$;

create or replace function search_clubs_v2(
  p_query text default '',
  p_country text default '',
  p_city text default '',
  p_postal_code text default '',
  p_club_type text default '',
  p_claim_status text default '',
  p_followed_only boolean default false,
  p_limit integer default 24,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path=public,extensions
as $$
declare
  viewer uuid:=current_member_profile_id();
  safe_query text:=normalize_search_text(left(trim(coalesce(p_query,'')),120));
  safe_country text:=normalize_search_text(upper(left(trim(coalesce(p_country,'')),80)));
  safe_city text:=normalize_search_text(left(trim(coalesce(p_city,'')),120));
  safe_postal text:=upper(left(trim(coalesce(p_postal_code,'')),32));
  safe_type text:=left(trim(coalesce(p_club_type,'')),40);
  safe_claim text:=left(trim(coalesce(p_claim_status,'')),40);
  safe_limit integer:=greatest(1,least(coalesce(p_limit,24),60));
  safe_offset integer:=greatest(0,least(coalesce(p_offset,0),1000000));
  result jsonb;
begin
  with matching as (
    select
      c.id,c.profile_id,c.official_name,c.short_name,c.slug,c.city,c.region,c.postal_code,c.address_line,
      c.latitude,c.longitude,c.founded_year,c.website_url,c.logo_url,c.colors,c.club_status,c.club_type,c.description,
      c.data_quality,c.claim_status,c.verification_status,c.followers_count,c.featured,
      co.name as country_name,co.iso2 as country_code,p.avatar_url,p.cover_url,
      exists(select 1 from club_follows f where f.club_id=c.id and f.profile_id=viewer) as followed,
      (select count(*)::integer from opportunities o where o.organization_profile_id=c.profile_id and o.status='open' and o.visibility='public' and (o.deadline is null or o.deadline>=current_date)) as open_opportunities,
      case
        when safe_query='' then 0
        when normalize_search_text(c.official_name)=safe_query then 100
        when normalize_search_text(coalesce(c.short_name,''))=safe_query then 98
        when c.normalized_name like safe_query||'%' then 90
        when c.search_vector @@ websearch_to_tsquery('simple',safe_query) then 80+ts_rank(c.search_vector,websearch_to_tsquery('simple',safe_query))*10
        else greatest(similarity(c.normalized_name,safe_query),0)*70
      end as rank_score
    from clubs c
    left join profiles p on p.id=c.profile_id
    left join countries co on co.id=c.country_id
    where (p.id is null or p.visibility='public')
      and (
        safe_query=''
        or c.search_vector @@ websearch_to_tsquery('simple',safe_query)
        or c.normalized_name % safe_query
        or c.normalized_name like '%'||safe_query||'%'
        or c.normalized_city like safe_query||'%'
        or coalesce(c.postal_code,'') like upper(safe_query)||'%'
        or exists(select 1 from club_aliases ca where ca.club_id=c.id and (ca.normalized_alias like '%'||safe_query||'%' or ca.normalized_alias % safe_query))
      )
      and (safe_country='' or normalize_search_text(coalesce(co.iso2,''))=safe_country or normalize_search_text(coalesce(co.name,''))=safe_country)
      and (safe_city='' or c.normalized_city=safe_city or c.normalized_city like safe_city||'%')
      and (safe_postal='' or coalesce(c.postal_code,'') like safe_postal||'%')
      and (safe_type='' or c.club_type=safe_type)
      and (safe_claim='' or c.claim_status=safe_claim)
      and (not coalesce(p_followed_only,false) or exists(select 1 from club_follows f where f.club_id=c.id and f.profile_id=viewer))
  ), counted as (
    select count(*)::integer total from matching
  ), paged as (
    select * from matching
    order by featured desc,rank_score desc,followers_count desc,official_name
    limit safe_limit offset safe_offset
  )
  select jsonb_build_object(
    'total',counted.total,
    'results',coalesce((select jsonb_agg(to_jsonb(paged) order by featured desc,rank_score desc,followers_count desc,official_name) from paged),'[]'::jsonb)
  ) into result from counted;

  return coalesce(result,jsonb_build_object('total',0,'results','[]'::jsonb));
end;
$$;

create or replace function get_data_attributions()
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'slug',slug,'name',name,'website_url',website_url,'license_name',license_name,
    'license_url',license_url,'attribution_text',attribution_text
  ) order by name),'[]'::jsonb)
  from data_sources where enabled=true;
$$;

alter table data_sources enable row level security;
alter table geographic_places enable row level security;
alter table place_aliases enable row level security;
alter table club_aliases enable row level security;
alter table club_external_ids enable row level security;
alter table data_import_jobs enable row level security;
alter table club_import_staging enable row level security;
alter table club_merge_candidates enable row level security;

revoke all on data_sources,geographic_places,place_aliases,club_aliases,club_external_ids,data_import_jobs,club_import_staging,club_merge_candidates from anon,authenticated;
revoke all on function search_places(text,text,integer) from public;
revoke all on function search_clubs_v2(text,text,text,text,text,text,boolean,integer,integer) from public;
revoke all on function get_data_attributions() from public;
grant execute on function search_places(text,text,integer) to anon,authenticated;
grant execute on function search_clubs_v2(text,text,text,text,text,text,boolean,integer,integer) to anon,authenticated;
grant execute on function get_data_attributions() to anon,authenticated;

-- Repair legacy seed strings that were previously committed with mojibake.
update clubs set official_name='Maghreb Association Sportive de Fès',city='Fès' where slug='maghreb-de-fes' and claim_status='unclaimed';
update clubs set official_name='Moghreb Athletic de Tétouan',city='Tétouan' where slug='moghreb-de-tetouan' and claim_status='unclaimed';
update clubs set official_name='Hassania Union Sport d''Agadir' where slug='hassania-agadir' and claim_status='unclaimed';
update clubs set official_name='Difaâ Hassani d''El Jadida' where slug='difaa-el-jadida' and claim_status='unclaimed';
update clubs set official_name='Club Omnisports de Meknès',city='Meknès' where slug='codm-meknes' and claim_status='unclaimed';
update clubs set official_name='Mouloudia Club d''Oujda' where slug='mouloudia-oujda' and claim_status='unclaimed';
update clubs set official_name='Kénitra Athletic Club',city='Kénitra' where slug='kenitra-athletic-club' and claim_status='unclaimed';
update clubs set official_name='Kawkab Athlétique Club de Marrakech' where slug='kawkab-marrakech' and claim_status='unclaimed';
update clubs set official_name='Chabab Mohammédia',city='Mohammédia' where slug='chabab-mohammedia' and claim_status='unclaimed';
update clubs set official_name='Chabab Atlas Khénifra',city='Khénifra' where slug='chabab-atlas-khenifra' and claim_status='unclaimed';

commit;
